# traefik/config.yml
http:
  routers:
    traefik:
      rule: "Host(`traefik.ot.localhost`)"
      service: "api@internal"
      tls:
        domains:
          - main: "ot.localhost"
            sans:
              - "*.ot.localhost"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
